# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Light', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Preso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Celda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcel.Celda')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Light', models.BooleanField()),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Permis', models.BooleanField()),
                ('Sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcel.Sector')),
            ],
        ),
        migrations.AddField(
            model_name='celda',
            name='Sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcel.Sector'),
        ),
    ]
