# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celda',
            name='idc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='celda',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='celda',
            unique_together=set([('idc', 'Sector')]),
        ),
    ]
