# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcel', '0002_auto_20180515_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celda',
            old_name='idc',
            new_name='numero',
        ),
        migrations.AlterField(
            model_name='celda',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='celda',
            unique_together=set([('numero', 'Sector')]),
        ),
    ]
