# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcel', '0004_auto_20180523_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='celda',
            name='Door',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='celda',
            name='Light',
            field=models.BooleanField(),
        ),
    ]
