# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carcel', '0003_auto_20180515_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celda',
            name='Light',
            field=models.BooleanField(default=False),
        ),
    ]
